api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('get/posts/', views.post_urls, name='post_urls'),
]

blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('all-blogs/', views.all_blogs, name='all_blogs'),
    path('blog-page/<str:blog_name>/<int:blog_id>/', views.blog_page, name='blog_page'),
    path('search/', views.search, name='search'),
    path('edit-blog/<int:blog_id>/', views.edit_blog, name='edit_blog'),
    path('cookies/', views.cookies),
]

portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('xxx/', admin.site.urls),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
]

from django.conf.urls.static import static
from django.conf import settings


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    POST_CATEGORIES_CHOICE = (
        ('Abdomen', 'Abdomen'),
        ('Torax', 'Torax'),
        ('Ginecología', 'Ginecología'),
        ('Pediatría', 'Pediatría'),
        ('Neurología', 'Neurología'),
        ('Musculoesquelético', 'Musculoesquelético'),
        ('Otras', 'Otras'),
    )

    MEDICAL_FINDINGS_CHOICES = (
        ('Alta (confirmación anatomopatológica/quirúrgica)', 'Alta (confirmación anatomopatológica/quirúrgica)'),
        ('Moderada', 'Moderada'),
        ('Baja', 'Baja'),
    )

    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=20, choices=POST_CATEGORIES_CHOICE, default='Abdomen')
    fisiopathology = models.TextField(blank=True, null=True)
    clinical_case = models.TextField(blank=True, null=True)
    clinical_signs = models.TextField(blank=True, null=True)
    doppler = models.TextField(blank=True, null=True)
    medical_findings = models.CharField(max_length=100, choices=MEDICAL_FINDINGS_CHOICES, default='Alta (confirmación anatomopatológica/quirúrgica)')
    preparation = models.TextField(blank=True, null=True)
    sequential = models.TextField(blank=True, null=True)
    pediatrics = models.TextField(blank=True, null=True)
    medical_report = models.TextField(blank=True, null=True)
    seram_link = models.URLField(blank=True, null=True)
    radiopedia_link = models.URLField(blank=True, null=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._meta.get_field('doppler').blank = not self.is_torax()

    def is_torax(self):
        return self.category == 'Torax'

blog/views.py
import pydicom
import os
from PIL import Image
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from users.models import FilePost
from .models import Post
from users.models import UserProfile
from users.forms import PostForm, FilePostForm

def cookies (request):

     return render(request, "aviso-cookies.html")

def home(request):
    posts = Post.objects.order_by('-date_posted')[:5]
    post_images = retrieve_first_post_image(posts)

    return render(request, 'blog/home.html', {'posts': posts, 'post_images': post_images})


def all_blogs(request):
    posts = Post.objects.order_by('-date_posted')
    paginator = Paginator(posts, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    post_images = retrieve_first_post_image(posts)

    return render(request, 'blog/all_blog_pages.html', {'post_images': post_images, 'page_obj': page_obj})


def blog_page(request, blog_name, blog_id):
    post = get_object_or_404(Post, id=blog_id)
    user_profile = UserProfile.objects.filter(user=post.author).first()
    if user_profile is not None:
        country = user_profile.country
        academic_year = user_profile.academic_year
        work_location = user_profile.work_location
        medical_specialty = user_profile.medical_specialty


    filepost = FilePost.objects.filter(post=post).first()
    files = FilePost.objects.filter(post=post)
    axial_post_images_list = list()
    coronal_post_images_list = list()
    sagital_post_images_list = list()
    axial_description = str()
    coronal_description = str()
    sagital_description = str()

    for file in files:
        if file.axial_images:
            axial_post_images_list.append(file.axial_images.url)
            if file.axial_description and file.axial_description != 'None':
                if not axial_description:
                    axial_description = file.axial_description
        if file.coronal_images:
            coronal_post_images_list.append(file.coronal_images.url)
            if file.coronal_description and file.coronal_description != 'None':
                if not coronal_description:
                    coronal_description = file.coronal_description
        if file.sagital_images:
            if file.sagital_description and file.sagital_description != 'None':
                if not sagital_description:
                    sagital_description = file.sagital_description
            sagital_post_images_list.append(file.sagital_images.url)

    if request.user == post.author:
        can_edit = True
    else:
        can_edit = False

    print(axial_description)

    return render(request, 'blog/blog_page.html', {'blog_name': blog_name, 'post': post, 'axial_post_images_list': axial_post_images_list, 'coronal_post_images_list': coronal_post_images_list, 'sagital_post_images_list': sagital_post_images_list, 'can_edit': can_edit, 'filepost': filepost, 'country': country, 'academic_year': academic_year, 'work_location': work_location, 'medical_specialty': medical_specialty, 'axial_description': axial_description, 'coronal_description': coronal_description, 'sagital_description': sagital_description})


def retrieve_first_post_image(posts):
    post_images = {}

    for post in posts:
        file = FilePost.objects.filter(post=post).first()
        if file is not None:
            post_images[post.id] = file.header_image.url

    return post_images

def search(request):
    query = request.GET.get('q')
    post_images = {}

    if query:
        posts = Post.objects.filter(Q(title__icontains=query) | Q(content__icontains=query)).order_by('-date_posted')
        post_images = retrieve_first_post_image(posts)
    else:
        posts = Post.objects.none()

    paginator = Paginator(posts, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'blog/search_blog.html', {'posts': posts, 'post_images': post_images, 'page_obj': page_obj, 'query': query})


@login_required(login_url='users:login')
def edit_blog(request, blog_id):
    post = get_object_or_404(Post, id=blog_id)
    if request.user != post.author:
        return redirect('blog:home')
    else:
        if request.method == 'POST':
            form = PostForm(request.POST, instance=post)
            form2 = FilePostForm(request.POST, request.FILES)
            axial_images = request.FILES.getlist('axial_image')
            coronal_images = request.FILES.getlist('coronal_image')
            sagital_images = request.FILES.getlist('sagital_image')
            header_image = request.FILES.get('header_image')

            if form.is_valid() and form2.is_valid():
                form.save()
                post_instance = Post.objects.get(id=blog_id)
                file_instance = FilePost.objects.filter(post=post_instance)
                file_instance.all().delete()
                image_format = form2.cleaned_data['format']
                accepted_data_use = form2.cleaned_data['accepted_data_use']
                cie_11_tagging = form2.cleaned_data['cie_11_tagging']
                interested_region = form2.cleaned_data['interested_region']
                other_interested_region = form2.cleaned_data['other_interested_region']
                axial_description = form2.cleaned_data['axial_description']
                coronal_description = form2.cleaned_data['coronal_description']
                sagital_description = form2.cleaned_data['sagital_description']
                error = False

                if accepted_data_use == 'No':
                    cie_11_tagging = None
                    interested_region = None
                    other_interested_region = None

                if image_format == 'DICOM':
                    try:
                        image_header_dicom = pydicom.dcmread(header_image)
                        image_header_array = image_header_dicom.pixel_array.astype(float)
                        new_image_header = Image.fromarray(image_header_array)
                        new_image_header = new_image_header.convert('L')
                        output_filename_header = header_image.name.split('.')[0] + '.jpg'
                        output_path_image_header = 'media/images/user_{0}/post_{1}/{2}'.format(post_instance.author.username, post_instance.pk, output_filename_header)
                        os.makedirs(os.path.dirname(output_path_image_header), exist_ok=True)
                        new_image_header.save(output_path_image_header, format='JPEG')
                        output_path_image_header = output_path_image_header.replace('media/', '')

                        if not [x for x in (axial_images, sagital_images, coronal_images) if x]:
                            FilePost.objects.create(post=post_instance, format=image_format, header_image=output_path_image_header, accepted_data_use=accepted_data_use, cie_11_tagging=cie_11_tagging, interested_region=interested_region, other_interested_region=other_interested_region)


                        for image_set in [axial_images, sagital_images, coronal_images]:
                            for image in image_set:
                                dicom_data = pydicom.dcmread(image)
                                image_array = dicom_data.pixel_array.astype(float)
                                img = Image.fromarray(image_array)
                                img = img.convert('L')
                                output_filename = image.name.split('.')[0] + '.jpg'
                                output_path_image = 'media/images/user_{0}/post_{1}/{2}'.format(post_instance.author.username, post_instance.pk, output_filename)
                                os.makedirs(os.path.dirname(output_path_image), exist_ok=True)
                                if accepted_data_use == 'Si':
                                    output_path_dicom_image = 'media/images/user_{0}/post_{1}/{2}'.format(post_instance.author.username, post_instance.pk, image.name)
                                    dicom_data.save_as(output_path_dicom_image)
                                img.save(output_path_image, format='JPEG')
                                output_path_image = output_path_image.replace('media/', '')

                                if image_set is axial_images:
                                    FilePost.objects.create(axial_images=output_path_image, post=post_instance, format=image_format, header_image=output_path_image_header, axial_description=axial_description, accepted_data_use=accepted_data_use, cie_11_tagging=cie_11_tagging, interested_region=interested_region, other_interested_region=other_interested_region)
                                elif image_set is sagital_images:
                                    FilePost.objects.create(sagital_images=output_path_image, post=post_instance, format=image_format, header_image=output_path_image_header, sagital_description=sagital_description, accepted_data_use=accepted_data_use, cie_11_tagging=cie_11_tagging, interested_region=interested_region, other_interested_region=other_interested_region)
                                else:
                                    FilePost.objects.create(coronal_images=output_path_image, post=post_instance, format=image_format, header_image=output_path_image_header, coronal_description=coronal_description, accepted_data_use=accepted_data_use, cie_11_tagging=cie_11_tagging, interested_region=interested_region, other_interested_region=other_interested_region)
                    except:
                        error = True

                else:

blog/templates/blog/all_blog_pages.html
{% extends "base.html" %}
{% load blogtags %}
{% block title %}Entradas - Portal RadiologyModels{% endblock %}
{% block content %}
<div class="page-wrapper">
    <div class="section light-page-header wf-section">
        <div class="container">
            <h1 class="heading large-h1">Entradas</h1>
        </div>
    </div>
    <div class="section wf-section">
        <div class="container">
            <div class="w-dyn-list">
                <div role="list" class="large-3-grid w-dyn-items">
                    {% for post in page_obj %}
                        <div role="listitem" class="post-box w-dyn-item"><a href="{% url 'blog:blog_page' post.title post.id %}" class="post-thumbnail w-inline-block"> <img src="{{ post_images|get_item:post.id }}" alt="{{post.title}}" class="image-cover" /></a>
                        <div class="paragraph small">{{post.author}}</div><a href="#" class="card-text-link w-inline-block"><h2 class="heading h3">{{post.title}}</h2><p class="paragraph small">{{post.content|truncatechars:100}}</p></a>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}" class="button w-button">Página anterior</a>
            {% endif %}
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="button w-button">Página siguiente</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/home.html
{% extends "base.html" %}
{% load blogtags %}
{% block title %}Home - Portal RadiologyModels{% endblock %}
{% block content %}
    <div class="page-wrapper">
        <div class="section light-color-gradient wf-section">
            <div class="container">
                <div class="w-layout-grid hero-grid">
                    <div class="text-box _500px">
                        <h1 class="heading h1">Entradas del servidor PORTAL.RADIOLOGYMODELS</h1>
                        <p class="paragraph large">Sube tus entradas para compartirlas con la comunidad. Se añadirán a RadiologyModels</p>
                        <div class="spacer _16"></div><a href="#entradas" class="button w-button">Ver últimas entradas</a>
                    </div>
                </div>
            </div>
        </div>
    <div id="entradas" class="section wf-section">
        <div class="container">
            <div class="section-top">
                <h2 class="heading h3">Ultimas entradas</h2>
                <a href="{% url 'blog:all_blogs' %}" class="button light mobile-hidden w-button">Ver todas las entradas</a>
            </div>
            <div class="w-dyn-list">
                <div role="list" class="large-3-grid w-dyn-items">
                    {% for post in posts %}
                        <div role="listitem" class="post-box w-dyn-item"><a href="{% url 'blog:blog_page' post.title post.id %}" class="post-thumbnail w-inline-block"> <img src="{{ post_images|get_item:post.id }}" alt="{{post.title}}" class="image-cover" /></a>
                        <div class="paragraph small">{{post.author}}</div><a href="{% url 'blog:blog_page' post.title post.id %}" class="card-text-link w-inline-block"><h2 class="heading h3">{{post.title}}</h2><p class="paragraph small">{{post.content|truncatechars:100}}</p></a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/search_blog.html
{% extends "base.html" %}
{% load blogtags %}
{% block title %}Buscar - Portal RadiologyModels{% endblock %}
{% block content %}
<div class="page-wrapper">
    <div class="section light-page-header wf-section">
        <div class="container">
            <h1 class="heading h1">Resultado de búsqueda</h1>
        </div>
    </div>
    <div class="section wf-section">
        <div class="container w-container">
            <div>
                <div class="large-3-grid search-result-items">
                {% for post in page_obj %}
                    <div class="post-box"><a href="{% url 'blog:blog_page' post.title post.id %}" class="post-thumbnail w-inline-block"><img src="{{ post_images|get_item:post.id }}" alt="{{post.title}}" class="image-cover" /></a>
                        <a href="{% url 'blog:blog_page' post.title post.id %}" class="card-text-link w-inline-block"><h2 class="heading h3">{{post.title}}</h2><p class="paragraph small">{{post.content|truncatechars:100}}</p></a>
                    </div>
                {% endfor %}
                </div>
            </div>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}&q={{query}}" class="button w-button">Página anterior</a>
            {% endif %}
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}&q={{query}}" class="button w-button">Página siguiente</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}