api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('get/posts/', views.post_urls, name='post_urls'),
]

portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('xxx/', admin.site.urls),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
]

from django.conf.urls.static import static
from django.conf import settings


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('profile/', views.user_dashboard, name='user_dashboard'),
    path('profile/edit/', views.update_user_profile, name='update_user_profile'),
    path('profile/new-post/', views.new_post, name='new_post'),
    path('activate/<uidb64>/<token>/', views.activate_user, name='activate_user'),
    path('reset-password/<uidb64>/<token>/', views.reset_password_confirm, name='reset_password_confirm'),
]

users/models.py
import pycountry
from django.db import models
from blog.models import Post
from django.contrib.auth.models import User
from django.db.models.fields import BLANK_CHOICE_DASH


def images_path(instance, filename):
    return 'images/user_{0}/post_{1}/{2}'.format(instance.post.author.username, instance.post.id, filename)

class UserProfile(models.Model):
    academic_year_list = ['Estudiante','R0', 'R1', 'R2','R3', 'R4','R5', 'Adjunto']
    medical_specialty_list = ['Radiología pediátrica', 'Radiología ginecológica','Radiología de abdomen', 'Neurorradiología', 'Radiología intervencionista', 'Radiología musculoesquelética', 'Radiología general']

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    country = models.CharField(max_length=100, choices=[(country.name, country.name) for country in pycountry.countries], blank=True, null=True)
    academic_year = models.CharField(max_length=100, choices=[(academic_year, academic_year) for academic_year in academic_year_list], blank=True, null=True)
    work_location = models.CharField(max_length=100, blank=True, null=True)
    medical_specialty = models.CharField(max_length=100, choices=[(medical_specialty, medical_specialty) for medical_specialty in medical_specialty_list], blank=True, null=True)

class FilePost(models.Model):
    USE_DATA_CHOICES = (
        ('Si', 'Si'),
        ('No', 'No'),
    )

    JPEG = 'JPEG'
    DICOM = 'DICOM'
    FORMAT_CHOICES = (
        ('JPEG, JPG', 'JPEG/JPG'),
        (DICOM, 'DICOM'),
    )

    INTERESTED_REGION_CHOICES = (
        BLANK_CHOICE_DASH[0],
        ('Segmento 1', 'Segmento 1'),
        ('Segmento 2', 'Segmento 2'),
        ('Segmento 3', 'Segmento 3'),
        ('Segmento 4', 'Segmento 4'),
        ('Segmento 5', 'Segmento 5'),
        ('Segmento 6', 'Segmento 6'),
        ('Segmento 7', 'Segmento 7'),
        ('Segmento 8', 'Segmento 8'),
        ('Difusa', 'Difusa'),
        ('Subcapsular', 'Subcapsular')
    )

    CIE_11_TAGGING_CHOICES = (
        BLANK_CHOICE_DASH[0],
        ('DB90 Enfermedad infecciosa del hígado', 'DB90 Enfermedad infecciosa del hígado'),
        ('DB91 Insuficiencia hepática aguda o subaguda', 'DB91 Insuficiencia hepática aguda o subaguda'),
        ('DB92/DB94 Hepatopatía grasa', 'DB92/DB94 Hepatopatía grasa'),
        ('DB93 Fibrosis o cirrosis hepática', 'DB93 Fibrosis o cirrosis hepática'),
        ('DB95 Hepatopatía tóxica o provocada por medicamentos', 'DB95 Hepatopatía tóxica o provocada por medicamentos'),
        ('DB96 Enfermedad hepática autoinmune', 'DB96 Enfermedad hepática autoinmune'),
        ('DB97 Algunas hepatopatías inflamatorias especificadas', 'DB97 Algunas hepatopatías inflamatorias especificadas'),
        ('DB98 Trastornos vasculares del hígado', 'DB98 Trastornos vasculares del hígado'),
        ('DB99 Algunas enfermedades especificadas del hígado', 'DB99 Algunas enfermedades especificadas del hígado'),
        ('Neoplasias del hígado', 'Neoplasias del hígado'),
        ('LB20.0 Anomalías estructurales del desarrollo prenatal del hígado', 'LB20.0 Anomalías estructurales del desarrollo prenatal del hígado'),
        ('5C90 Enfermedad hepática metabólica o transportadora', '5C90 Enfermedad hepática metabólica o transportadora'),
        ('Hepatitis viral', 'Hepatitis viral'),
        ('DB9Z Enfermedades del hígado, sin especificación', 'DB9Z Enfermedades del hígado, sin especificación'),
        ('Otras', 'Otras'),
    )

    POST_CATEGORIES_CHOICE = (
        ('Abdomen', 'Abdomen'),
        ('Torax', 'Torax'),
        ('Ginecología', 'Ginecología'),
        ('Pediatría', 'Pediatría'),
        ('Neurología', 'Neurología'),
        ('Musculoesquelético', 'Musculoesquelético'),
        ('Otras', 'Otras'),
    )

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    format = models.CharField(max_length=9, choices=FORMAT_CHOICES, null=True, blank=True)
    axial_images = models.ImageField(upload_to=images_path, null=True, blank=True)
    axial_description = models.CharField(max_length=500, blank=True, null=True)
    coronal_images = models.ImageField(upload_to=images_path, null=True, blank=True)
    category = models.CharField(max_length=20, choices=POST_CATEGORIES_CHOICE, default='Abdomen')
    coronal_description = models.CharField(max_length=500, blank=True, null=True)
    sagital_images = models.ImageField(upload_to=images_path, null=True, blank=True)
    sagital_description = models.CharField(max_length=500, blank=True, null=True)
    header_image = models.ImageField(upload_to=images_path)
    accepted_data_use = models.CharField(max_length=2, choices=USE_DATA_CHOICES, blank=True, null=True)
    cie_11_tagging = models.CharField(max_length=100, choices=CIE_11_TAGGING_CHOICES, blank=True, null=True)
    interested_region = models.CharField(max_length=100, choices=INTERESTED_REGION_CHOICES, blank=True, null=True)
    other_interested_region = models.CharField(max_length=100, blank=True, null=True)

users/views.py
import pydicom
import os
from PIL import Image
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
from django.db import transaction
from django.contrib.sites.shortcuts import get_current_site
from django.conf import settings
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from users.helpers.tokens import account_activation_token, reset_password_token
from django.template.loader import render_to_string
from django.urls import reverse
from .forms import SignupForm, LoginForm, ResetPasswordForm, ChangePasswordForm, PostForm, FilePostForm, UserUpdateForm
from .models import Post, FilePost, UserProfile
from django.contrib.auth.models import User
from blog.models import Post
from blog.views import retrieve_first_post_image

def login(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect(reverse('users:user_dashboard'))

        else:
            form = LoginForm()
            return render(request, 'users/login.html', {'form': form})

    elif request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = User.objects.filter(email=form.cleaned_data['email']).first()
            if user and user.check_password(form.cleaned_data['password']):
                if user.is_active:
                    auth_login(request, user)
                    return redirect(reverse('users:user_dashboard'))
                else:
                    return render(request, 'users/login.html', {'form': form, 'error_message': 'Tu cuenta no está activa. Revisa tu correo electrónico para activarla.'})
            else:
                return render(request, 'users/login.html', {'form': form, 'error_message': 'Correo o contraseña incorrectos.'})
        else:
            return render(request, 'users/login.html', {'form': form})

    else:
        return redirect('blog:home')

def logout(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            auth_logout(request)
            return redirect(reverse('users:login'))
        else:
            return redirect(reverse('users:login'))
    else:
        return redirect('blog:home')

def signup(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect(reverse('users:user_dashboard'))

        form = SignupForm()
        return render(request, 'users/signup.html', {'form': form})

    elif request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.password = make_password(form.cleaned_data['password1'])
            user.is_active = False
            user.save()

            UserProfile.objects.create(user=user)

            current_site = get_current_site(request)

            subject = render_to_string('users/activation_email_subject.txt')
            message = render_to_string('users/activation_email_message.txt', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })

            send_mail(
                subject,
                message,
                settings.DEFAULT_FROM_EMAIL,
                [user.email],
                fail_silently=False,
            )

            if user.email:
                msg = 'Usuario creado correctamente. Verifica tu correo electrónico para activar la cuenta.'

            else:
                msg = 'Error al crear el usuario. Por favor intenta de nuevo.'

            return render(request, 'users/signup.html', {'message': msg})
        else:
            return render(request, 'users/signup.html', {'form': form})

    else:
        return redirect('blog:home')

def update_user_profile(request):
    if not request.user.is_authenticated:
        return redirect(reverse('users:login'))
    else:
        if request.method == 'GET':
            form = ChangePasswordForm()
            form2 = UserUpdateForm()
            get_current_user_mail = request.user.email
            return render(request, 'users/user_dashboard.html', {'form': form, 'form2': form2, 'email': get_current_user_mail})

        elif request.method == 'POST':
            form = ChangePasswordForm()
            form2 = UserUpdateForm(request.POST)
            if form2.is_valid():
                user = User.objects.get(email=request.user.email)
                country = form2.cleaned_data['user_country']
                academic_year = form2.cleaned_data['user_academic_year']
                work_location = form2.cleaned_data['user_work_location']
                medical_specialty = form2.cleaned_data['user_medical_specialty']

                UserProfile.objects.filter(user=user).update(country=country, academic_year=academic_year, work_location=work_location, medical_specialty=medical_specialty)

                get_current_user_mail = request.user.email
                message = 'Información actualizada correctamente.'

                return render(request, 'users/user_dashboard.html', {'message': message, 'form': form, 'form2': form2, 'email': get_current_user_mail})
            else:
                get_current_user_mail = request.user.email
                return render(request, 'users/user_dashboard.html', {'form': form, 'form2': form2, 'email': get_current_user_mail})

        else:
            return redirect('blog:home')

def user_dashboard(request):
    if not request.user.is_authenticated:
        return redirect(reverse('users:login'))
    else:
        if request.method == 'GET':
            form = ChangePasswordForm()
            form2 = UserUpdateForm()
            get_current_user_mail = request.user.email
            return render(request, 'users/user_dashboard.html', {'form': form, 'form2': form2, 'email': get_current_user_mail})

        elif request.method == 'POST':
            form = ChangePasswordForm(request.POST)
            form2 = UserUpdateForm()
            if form.is_valid():
                user = User.objects.get(email=request.user.email)
                user.password = make_password(form.cleaned_data['password1'])
                user.save()

                get_current_user_mail = request.user.email
                message = 'Contraseña actualizada correctamente.'

                auth_login(request, user)

                return render(request, 'users/user_dashboard.html', {'message': message, 'form': form, 'form2': form2, 'email': get_current_user_mail})
            else:
                get_current_user_mail = request.user.email
                return render(request, 'users/user_dashboard.html', {'form': form, 'form2': form2, 'email': get_current_user_mail})

        else:
            return redirect('blog:home')

@transaction.atomic
def new_post(request):
    if not request.user.is_authenticated:
        return redirect(reverse('users:login'))
    else:
        if request.method == 'GET':
            form = PostForm()
            form2 = FilePostForm()
            return render(request, 'users/create_posts.html', {'form': form, 'form2': form2, 'show_popup': True})

        elif request.method == 'POST':
            form = PostForm(request.POST)
            form2 = FilePostForm(request.POST, request.FILES)
            axial_images = request.FILES.getlist('axial_image')
            coronal_images = request.FILES.getlist('coronal_image')
            sagital_images = request.FILES.getlist('sagital_image')
            header_image = request.FILES.get('header_image')

            if form.is_valid() and form2.is_valid():
                title = form.cleaned_data['title']
                content = form.cleaned_data['content']
                category = form.cleaned_data['category']
                image_format = form2.cleaned_data['format']
                fisiopathology = form.cleaned_data['fisiopathology']
                clinical_case = form.cleaned_data['clinical_case']
                clinical_signs = form.cleaned_data['clinical_signs']
                doppler = form.cleaned_data['doppler']
                sequential = form.cleaned_data['sequential']
                preparation = form.cleaned_data['preparation']
                pediatrics = form.cleaned_data['pediatrics']
                medical_report = form.cleaned_data['medical_report']
                seram_link = form.cleaned_data['seram_link']
                radiopedia_link = form.cleaned_data['radiopedia_link']
                accepted_data_use = form2.cleaned_data['accepted_data_use']
                cie_11_tagging = form2.cleaned_data['cie_11_tagging']
                interested_region = form2.cleaned_data['interested_region']
                other_interested_region = form2.cleaned_data['other_interested_region']
                axial_description = form2.cleaned_data['axial_description']
                coronal_description = form2.cleaned_data['coronal_description']
                sagital_description = form2.cleaned_data['sagital_description']
                error = False

                if accepted_data_use == 'No':
                    cie_11_tagging = None
                    interested_region = None
                    other_interested_region = None

                post_instance = Post.objects.create(title=title, content=content, category=category, author=request.user, fisiopathology=fisiopathology, clinical_case=clinical_case, clinical_signs=clinical_signs, doppler=doppler, preparation=preparation, pediatrics=pediatrics, medical_report=medical_report, seram_link=seram_link, radiopedia_link=radiopedia_link)

                if image_format == 'DICOM':

users/templates/users/login.html
{% extends "base.html" %}
{% block title %}Inicio de sesión - Portal RadiologyModels{% endblock %}
{% block content %}
<div class="w-users-userformpagewrap full-page-wrapper">
    <div class="w-users-userloginformwrapper admin-form-card">
        <form id="login_form" method="post" action="{% url 'users:login' %}">
            {% csrf_token %}
            <div class="w-users-userformheader form-card-header">
                <h2 class="heading h3">Log in</h2>
            </div>
            {%for field in form%}
            <input type={{field.field.widget.input_type}} class="text-field w-input" placeholder={{field.label}}
                name={{field.name}} id={{field.name}} required>
            {%endfor%}
            <input type="submit" value="Log In" class="w-users-userformbutton button w-button" />
            <div class="w-users-userformfooter form-card-footer"><span>¿No tienes cuenta?</span><a
                    href="{% url 'users:signup' %}">Registrate</a><a href="{% url 'users:reset_password' %}" class="below-card-link">¿Has olvidado tu contraseña?</a></div>
        </form>
        {%if error_message%}
        <div style="display:block" class="w-users-userformerrorstate w-form-fail">
            <div class="user-form-error-msg">
                {{error_message}}
            </div>
        </div>
        {%endif%}
    </div>
</div>
{% endblock %}

users/templates/users/reset_password.html
{% extends "base.html" %}
{% block title %}Restablecer contraseña - Portal RadiologyModels{% endblock %}
{% block content %}
<div class="w-users-userformpagewrap full-page-wrapper">
    <div class="w-users-userloginformwrapper admin-form-card">
        {% if not message %}
        {% if change_password%}
        <form id="reset_password_form" method="post" action="{% url 'users:reset_password_confirm' uidb64 token%}">
        {%else%}
        <form id="reset_password_form" method="post" action="{% url 'users:reset_password' %}">
        {%endif%}
            {% csrf_token %}
            <div class="w-users-userformheader form-card-header">
                {%if change_password%}
                <h2 class="heading h3">Cambiar contraseña</h2>
                <p class="paragraph small">Introduce tu nueva contraseña.</p>
                {%else%}
                <h2 class="heading h3">Restablecer contraseña</h2>
                <p class="paragraph small">Introduce tu correo electrónico y te enviaremos un enlace para restablecer tu contraseña.</p>
                {%endif%}
            </div>
            {%for field in form%}
            <input type={{field.field.widget.input_type}} class="text-field w-input" placeholder={{field.label}}
                name={{field.name}} id={{field.name}} required>
            {%endfor%}
            {%if change_password%}
            <input type="submit" value="Cambiar contraseña" class="w-users-userformbutton button w-button" />
            {%else%}
            <input type="submit" value="Restablecer contraseña" class="w-users-userformbutton button w-button" />
            <div class="w-users-userformfooter form-card-footer"><a href="{% url 'users:login' %}" class="below-card-link">Volver al inicio de sesión</a></div>
            {%endif%}
        </form>
        {% endif %}
        {% for field, errors in form.errors.items %}
        {% for error in errors %}
        <div style="display:block" class="w-users-userformerrorstate w-form-fail">
            <div class="user-form-error-msg">
                {{error}}
            </div>
        </div>
        {% endfor %}
        {% endfor %}
        {%if message%}
            <div>{{message}}</div>
        {%endif%}
    </div>
</div>
{% endblock %}

users/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Registro - Portal RadiologyModels{% endblock %}
{% block content %}
<div class="w-users-userformpagewrap full-page-wrapper">
    <div class="w-users-usersignupformwrapper admin-form-card">
        {% if not message %}
        <form id="signup_form" method="post" action="{% url 'users:signup' %}">
            {% csrf_token %}
            <div class="w-users-userformheader form-card-header">
                <h2 class="heading h3">Registro</h2>
            </div>
            {%for field in form%}
            <input type={{field.field.widget.input_type}} class="text-field w-input" placeholder={{field.label}}
                name={{field.name}} id={{field.name}} required>
            {%endfor%}
            <input type="submit" value="Registrarse" class="w-users-userformbutton button w-button" />
            <div class="w-users-userformfooter form-card-footer"><span>¿Ya tienes una cuenta?</span><a
                    href="{% url 'users:login' %}">Inicia sesión</a></div>
        </form>
        {% endif %}
        {% for field, errors in form.errors.items %}
        {% for error in errors %}
        <div style="display:block" class="w-users-userformerrorstate w-form-fail">
            <div class="user-form-error-msg">
                {{error}}
            </div>
        </div>
        {% endfor %}
        {% endfor %}
        {%if message%}
            <div>{{message}}</div>
        {%endif%}
    </div>
</div>
{% endblock %}

users/templates/users/user_dashboard.html
{% extends "base.html" %}
{% block title %}Panel de usuario - Portal RadiologyModels{% endblock %}
{% block content %}
<div class="page-wrapper">
    <div class="section wf-section">
        <div class="container">
            <h2 class="heading h2">Bienvenido {{user.username}}</h2>
            <div class="w-form">
                <form id="user_update_form" method="post" action="{% url 'users:user_dashboard' %}">
                    {% csrf_token %}
                    <div class="w-users-userformheader form-card-header">
                        <h2 class="heading h3">Actualizar información</h2>
                    </div>
                    {%for field in form%}
                        <input type={{field.field.widget.input_type}} class="text-field w-input" placeholder={{field.label}} name={{field.name}} id={{field.name}}>
                    {%endfor%}
                    <input type="submit" value="Actualizar contraseña" class="w-users-userformbutton button w-button" />
                </form>
                <form id="user_update_form" method="post" action="{% url 'users:update_user_profile' %}">
                    {% csrf_token %}
                    {%for field in form2%}
                        {% if field.name == 'user_work_location' %}
                            <label for="hospital">Hospital de trabajo</label>
                            <input type="text" class="text-field w-input" name={{field.name}} id={{field.name}} placeholder="Ejemplo: Hospital Universitario de Salamanca"></input>
                        {%else%}
                            <label for="country">{{ field.label }}</label>
                            <select name="{{ field.name }}" id="{{ field.id_for_label }}" class="w-select">
                                {% for choice in field.field.choices %}
                                    <option value="{{ choice.0 }}" {% if choice.0 == field.value %}selected{% endif %}>{{ choice.1 }}</option>
                                {% endfor %}
                            </select>
                        {%endif%}
                    {%endfor%}
                    <input type="submit" value="Actualizar información" class="w-users-userformbutton button w-button" />
                </form>
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <div style="display:block" class="w-users-userformerrorstate w-form-fail"><div class="user-form-error-msg">{{error}}</div></div>
                    {% endfor %}
                {% endfor %}
                {%if message%}
                    <div class="alert alert-success" role="alert">{{message}}</div>
                {%endif%}
            </div>
        </div>
    </div>
</div>
{% endblock %}