api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('get/posts/', views.post_urls, name='post_urls'),
]

blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('all-blogs/', views.all_blogs, name='all_blogs'),
    path('blog-page/<str:blog_name>/<int:blog_id>/', views.blog_page, name='blog_page'),
    path('search/', views.search, name='search'),
    path('edit-blog/<int:blog_id>/', views.edit_blog, name='edit_blog'),
    path('cookies/', views.cookies),
]

portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('xxx/', admin.site.urls),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
]

from django.conf.urls.static import static
from django.conf import settings


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('profile/', views.user_dashboard, name='user_dashboard'),
    path('profile/edit/', views.update_user_profile, name='update_user_profile'),
    path('profile/new-post/', views.new_post, name='new_post'),
    path('activate/<uidb64>/<token>/', views.activate_user, name='activate_user'),
    path('reset-password/<uidb64>/<token>/', views.reset_password_confirm, name='reset_password_confirm'),
]

templates/403_csrf.html
{% extends "base.html" %}
{% block title %}Error - Portal RadiologyModels{% endblock %}
{% block content %}
<div class="utility-page-wrap">
    <div class="utility-page-content w-form">
        <h1 class="heading h1">Acceso no autorizado</h1>
        <p class="paragraph">La página a la que intentas acceder necesita autenticación.</p>
        <div class="spacer _24"></div><a href="/" class="button white w-button">Inicio</a>
    </div>
</div>
{% endblock %}

templates/aviso-cookies.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Aviso de Privacidad</title>
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet"> 
	
</head>
<body>
	<main>
		
		<h1>Aviso de Cookies</h1>
		<h3>¿Qué son las cookies?</h3>
		<p>Una cookie es un fichero que se descarga en su ordenador al acceder a determinadas páginas web. Las cookies permiten a una página web, entre otras cosas, almacenar y recuperar información sobre los hábitos de navegación de un usuario o de su equipo y, dependiendo de la información que contengan y de la forma en que utilice su equipo, pueden utilizarse para reconocer al usuario.</p>

		<h3>¿Qué tipos de cookies utiliza esta página web?</h3>
		<p>Esta página web utiliza los siguientes tipos de cookies:</p>

		<p><b>Cookies de análisis:</b> Son aquéllas que bien tratadas por nosotros o por terceros, nos permiten cuantificar el número de usuarios y así realizar la medición y análisis estadístico de la utilización que hacen los usuarios del servicio ofertado. Para ello se analiza su navegación en nuestra página web con el fin de mejorar la oferta de productos o servicios que le ofrecemos.</p>

		<p><b>Cookies técnicas:</b> Son aquellas que permiten al usuario la navegación a través del área restringida y la utilización de sus diferentes funciones, como por ejemplo, llevar a cambio el proceso de compra de un artículo.</p>

		<p><b>Cookies de personalización:</b> Son aquellas que permiten al usuario acceder al servicio con algunas características de carácter general predefinidas en función de una serie de criterios en el terminal del usuario como por ejemplo serian el idioma o el tipo de navegador a través del cual se conecta al servicio.</p>

		<p><b>Cookies publicitarias:</b> Son aquéllas que, bien tratadas por esta web o por terceros, permiten gestionar de la forma más eficaz posible la oferta de los espacios publicitarios que hay en la página web, adecuando el contenido del anuncio al contenido del servicio solicitado o al uso que realice de nuestra página web. Para ello podemos analizar sus hábitos de navegación en Internet y podemos mostrarle publicidad relacionada con su perfil de navegación.</p>

		<p><b>Cookies de publicidad comportamental:</b> Son aquellas que permiten la gestión, de la forma más eficaz posible, de los espacios publicitarios que, en su caso, el editor haya incluido en una página web, aplicación o plataforma desde la que presta el servicio solicitado. Este tipo de cookies almacenan información del comportamiento de los visitantes obtenida a través de la observación continuada de sus hábitos de navegación, lo que permite desarrollar un perfil específico para mostrar avisos publicitarios en función del mismo.</p>

 
		<h3>Desactivar las cookies.</h3>
		<p>Puede usted permitir, bloquear o eliminar las cookies instaladas en su equipo mediante la configuración de las opciones del navegador instalado en su ordenador.</p>

		<p>En la mayoría de los navegadores web se ofrece la posibilidad de permitir, bloquear o eliminar las cookies instaladas en su equipo.</p>

		<p>A continuación puede acceder a la configuración de los navegadores webs más frecuentes para aceptar, instalar o desactivar las cookies:</p>

		<p><a href="https://support.google.com/chrome/answer/95647?hl=es" target="_blank" rel="noopener">Configurar cookies en Google Chrome</a></p>

		<p><a href="http://windows.microsoft.com/es-es/windows7/how-to-manage-cookies-in-internet-explorer-9" target="_blank" rel="noopener">Configurar cookies en Microsoft Internet Explorer</a></p>

		<p><a href="https://support.mozilla.org/es/kb/habilitar-y-deshabilitar-cookies-sitios-web-rastrear-preferencias?redirectlocale=es&amp;redirectslug=habilitar-y-deshabilitar-cookies-que-los-sitios-we" target="_blank" rel="noopener">Configurar cookies en Mozilla Firefox</a></p>

		<p><a href="https://support.apple.com/es-es/HT201265" target="_blank" rel="noopener">Configurar cookies en Safari (Apple)</a></p>

 
		<h3>Cookies de terceros.</h3>

		<p>Esta página web utiliza servicios de terceros para recopilar información con fines estadísticos y de uso de la web. Se usan cookies de DoubleClick para mejorar la publicidad que se incluye en el sitio web. Son utilizadas para orientar la publicidad según el contenido que es relevante para un usuario, mejorando así la calidad de experiencia en el uso del mismo.</p>

		<p>En concreto, usamos los servicios de Google Adsense y de Google Analytics para nuestras estadísticas y publicidad. Algunas cookies son esenciales para el funcionamiento del sitio, por ejemplo el buscador incorporado.</p>

		<p>Nuestro sitio incluye otras funcionalidades proporcionadas por terceros. Usted puede fácilmente compartir el contenido en redes sociales como Facebook, Twitter o Google +, con los botones que hemos incluido a tal efecto.</p>

 
		<h3>Advertencia sobre eliminar cookies.</h3>

		<p>Usted puede eliminar y bloquear todas las cookies de este sitio, pero parte del sitio no funcionará o la calidad de la página web puede verse afectada.</p>

		<p>Si tiene cualquier duda acerca de nuestra política de cookies, puede contactar con esta página web a través de nuestros canales de Contacto.</p>
	</main>
</body>
</html>

templates/base.html
{% load static %}
 
<!DOCTYPE html>

<html lang="en">
    <head>
        <!-- Google Tag Manager -->
        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-MDB536D');</script>
            <!-- End Google Tag Manager -->
            <script async src="https://www.googletagmanager.com/gtag/js?id=G-W4JPY8JBGY"></script>
            <script>
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());

                gtag('config', 'G-W4JPY8JBGY');
            </script>

    
        <meta charset="utf-8" />
        <title>
            {% block title %}{% endblock %}
        </title>

        {# Global stylesheets #}
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link href="https://fonts.googleapis.com" rel="preconnect" />
        <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin="anonymous" />
        <link href="{% static 'images/LOGUI.ico' %}" rel="shortcut icon" type="image/x-icon" />
        <link href="{% static 'images/LOGUI.ico' %}" rel="apple-touch-icon" />

        {% block extra_css %}
        {# Override this in templates to add extra stylesheets #}
        {% endblock %}
    </head>

    <body>
                <!-- Google Tag Manager (noscript) -->
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MDB536D"
            height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
            <!-- End Google Tag Manager (noscript) -->
    
        <body>
            <div data-collapse="small" data-animation="default" data-duration="400" data-easing="ease" data-easing2="ease"
              role="banner" class="nav-bar w-nav">
              <div class="nav-container w-container">
                <div class="logito"><a href="https://radiologymodels.com/" aria-current="page" class="nav-logo w-inline-block w--current"><img
                      src="{% static 'images/logonrecred1.png' %}" height="50" class="logito" /></a></div>
                <nav role="navigation" class="nav-content w-nav-menu">
                  <div class="search-banner">
                    <div class="search-section">
                      <form action="{% url 'blog:search' %}" method="get" class="search w-form"><input type="text" name="q" class="search-bar w-input" maxlength="256" placeholder="Buscar entradas" id="search" /><input type="submit" value="Search"class="hidden w-button" /></form>
                    </div>
                  </div>
                  <div class="nav-menu">
                    <a href="/" class="nav-link w-nav-link">Home</a>
                    {% if user.is_authenticated %}
                    <a href="{% url 'users:user_dashboard' %}" class="nav-link w-nav-link">Perfil</a>
                    <a href="{% url 'users:new_post' %}" class="nav-link w-nav-link">Nueva entrada</a>
                    <a href="{% url 'users:logout' %}" class="nav-link w-nav-link">Log out</a>
                    {% else %}
                    <a href="{% url 'users:login' %}" class="nav-link w-nav-link">Log in</a>
                    <a href="{% url 'users:signup' %}" class="nav-link w-nav-link">Registro</a>
                    {% endif %}
                </div>
                </nav>
                <div class="menu-button w-nav-button"><img src="{% static 'images/menu-icon.svg' %}" loading="lazy" width="24" alt=""
                    class="menu-icon" /></div>
              </div>
            </div>

        {% block content %}{% endblock %}

        <div class="footer wf-section">
            <div class="footer-container w-container">
                <div class="w-layout-grid footer-grid">
                    <div id="w-node-b8d7be4a-ce45-83ab-5947-02d204c8bff0-cf3fcb86" class="footer-logo-block"><a data-ix="logo"
                            href="/" aria-current="page" class="footer-logo w-nav-brand w--current"><img
                                src="{% static 'images/logo.png' %}" width="204" alt="" /></a>
                        <p class="paragraph small">Gracias por haber visitado nuestra aplicación.<br /></p>
                        <div class="spacer _16"></div>
                        <div class="paragraph small">Copyright © 2022 RadiologyModels.</div>
                    </div>
                </div>
            </div>
        </div>
                <!-- cookies-->
        <div class="aviso-cookies" id="aviso-cookies">
             
            <h3 class="titulo">Cookies</h3>
            <p class="parrafo">Utilizamos cookies propias y de terceros para mejorar nuestros servicios.</p>
            <button class="boton" id="btn-aceptar-cookies">De acuerdo</button>
            <a class="enlace" href="/cookies" >Aviso de Cookies</a>

        </div>
        <div class="fondo-aviso-cookies" id="fondo-aviso-cookies"></div>


          {# Global javascript #}
          <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=6499c9ce41e50262a4e2b90e"
          type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
          crossorigin="anonymous"></script>
          <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
          <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
          <script
              type="text/javascript">WebFont.load({ google: { families: ["Inter:regular,500,600,700", "Libre Baskerville:regular,italic,700", "Volkhov:regular,italic,700,700italic", "Noto Serif:regular,italic,700,700italic"] } });</script>
          <script
              type="text/javascript">!function (o, c) { var n = c.documentElement, t = " w-mod-"; n.className += t + "js", ("ontouchstart" in o || o.DocumentTouch && c instanceof DocumentTouch) && (n.className += t + "touch") }(window, document);</script>
          {% block extra_js %}
          {# Override this in templates to add extra javascript #}
          {% endblock %}
      </body>
  </html>